{1:"Za Temerię zrobię wszystko, nawet się skurwię.",
2:"Geralt, ty się znasz! Da radę wytresować smoka?",
3:"Lambert jest piękny o tej porze roku.",
4:"Wypij moje zdrowie! Zdrowie kurwiego syna Vernona Roche'a!",
5:"Użyj znaków! Złap go w Yrden!",
6:"Kto to Kasia",
7:"Cholera, Eskel! Masz talię osy!",
8:"Chlej z podłogi piwo od kurwiego syna!",
9:"No to jak kurwa będzie, robimy interes?",
10:"No raczej, kurwa, nie inaczej, gratuluję dedukcji, kurwa mać.",
11:"Ja, kurwa, jestem, a nie bywam.",
12:"Stolica kultury, kurwa mać.",
13:"Świat się zmienia, słońce zachodzi, a wódka się kończy.",
14:"A pocałujcie wy mnie wszyscy w dupę.",
15:"Jebać Nilfgaard.",
16:"Przynajmniej zginę z ręką na ślicznym tyłeczku!",
17:"Lambert, Lambert, ty 🌟chuju🌟!",
18:"- Oddawaj moje rzeczy, bo zabiję. - To chyba rym biały.",
19:"Kutasa mam jednego, na półtora metra.",
20:"Założyłem pionowe pasy, bo wiesz, wyszczuplają. No i poszedłem na dziwki.",
21:"Alvin jest lepszą dupą z twarzy niż Ciri - Letki, prawdopodobnie.",
22:"Smok był kroplą która przegięła pałę goryczy!",
23:"Strzyg, wiwern, endriag i wilkołaków wkrótce nie będzie na świecie. A skurwysyny będą zawsze.",
24:"Przychodzi kiedyś taki czas, gdy trzeba albo srać albo oswobodzić wychodek.",
25:"- Miecz. Na plecach. Dlaczego masz na plecach miecz? - Bo wiosło mi ukradli.",
26:"Poglądy są jak dupa, każdy jakieś ma, ale po co od razu pokazywać.",
27:"Gówno i kapusta zawsze w parze idą - rzekł sentencjonalnie Percival Schuttenbach. - Jedno popędza drugie. Perpetuum mobile.",
28:"Każdy szermierz dupa, kiedy wrogów kupa.",
29:"A czy ty wiesz, Dijkstra, że mieć milion i nie mieć miliona to razem dwa miliony?",
30:"Jedno, co można zrobić, to podejść do rzeczy filozoficznie, czyli powiedzieć sobie: srał to pies.",
31:"Wiesz Ciri, jak człowiekowi utną głowę, to można od tego umrzeć.",
32:"Nazywał się pies, i mówią że jebał twoją matkę.",
33:"Ja nie mieszam, ja zmagam się z tworzywem.",
34:"Gdy cię mają wieszać, poproś o szklankę wody. Nigdy nie wiadomo, co się wydarzy, zanim przyniosą.",
35:"Cofnąć się! Zabraniam wam umierać jak idioci",
36:"Mam cię w dupie tak głęboko, że trzeba by sztygara z Mahakamu, żeby się do ciebie dokopać.",
37:"Nigdy nie ma się drugiej okazji, żeby zrobić pierwsze wrażenie. Chodź, napijemy się lepiej piwa.",
38:"- Rzekł wtedy mężny Foltest: Cny Radowidzie... - Jaskier... co ty pieprzysz?",
39:"Nie czas żałować kapusty, gdy płonie las.",
40:"Dziad zdjął z głowy wielką futrzaną czapę i dostojnie roztoczył wokół siebie smród.",
41:"Gdzie ogiery kastrują tam nie zaszkodzi uważać i na własne jajca.",
42:"Zapachniało powiewem jesieni, Z wiatrem zimnym uleciał słów sens. Tak być musi, niczego nie mogą już zmienić Brylanty na końcach Twych rzęs."}
