a=["Dummy",
"Za Temerię zrobię wszystko, nawet się skurwię.",
"Geralt, ty się znasz! Da radę wytresować smoka?",
"Lambert jest piękny o tej porze roku.",
"Wypij moje zdrowie! Zdrowie kurwiego syna Vernona Roche'a!",
"Użyj znaków! Złap go w Yrden!",
"Kto to Kasia",
"Cholera, Eskel! Masz talię osy!",
"Chlej z podłogi piwo od kurwiego syna!",
"No to jak kurwa będzie, robimy interes?",
"No raczej, kurwa, nie inaczej, gratuluję dedukcji, kurwa mać.",
"Ja, kurwa, jestem, a nie bywam.",
"Stolica kultury, kurwa mać.",
"Świat się zmienia, słońce zachodzi, a wódka się kończy.",
"A pocałujcie wy mnie wszyscy w dupę.",
"Jebać Nilfgaard.",
"Przynajmniej zginę z ręką na ślicznym tyłeczku!",
"Lambert, Lambert, ty 🌟chuju🌟!",
"- Oddawaj moje rzeczy, bo zabiję. - To chyba rym biały.",
"Kutasa mam jednego, na półtora metra.",
"Założyłem pionowe pasy, bo wiesz, wyszczuplają. No i poszedłem na dziwki.",
"Alvin jest lepszą dupą z twarzy niż Ciri - Letki, prawdopodobnie.",
"Smok był kroplą która przegięła pałę goryczy!",
"Strzyg, wiwern, endriag i wilkołaków wkrótce nie będzie na świecie. A skurwysyny będą zawsze.",
"Przychodzi kiedyś taki czas, gdy trzeba albo srać albo oswobodzić wychodek.",
"- Miecz. Na plecach. Dlaczego masz na plecach miecz? - Bo wiosło mi ukradli.",
"Poglądy są jak dupa, każdy jakieś ma, ale po co od razu pokazywać.",
"Gówno i kapusta zawsze w parze idą - rzekł sentencjonalnie Percival Schuttenbach. - Jedno popędza drugie. Perpetuum mobile.",
"Każdy szermierz dupa, kiedy wrogów kupa.",
"A czy ty wiesz, Dijkstra, że mieć milion i nie mieć miliona to razem dwa miliony?",
"Jedno, co można zrobić, to podejść do rzeczy filozoficznie, czyli powiedzieć sobie: srał to pies.",
"Wiesz Ciri, jak człowiekowi utną głowę, to można od tego umrzeć.",
"Nazywał się pies, i mówią że jebał twoją matkę.",
"Ja nie mieszam, ja zmagam się z tworzywem.",
"Gdy cię mają wieszać, poproś o szklankę wody. Nigdy nie wiadomo, co się wydarzy, zanim przyniosą.",
"Cofnąć się! Zabraniam wam umierać jak idioci",
"Mam cię w dupie tak głęboko, że trzeba by sztygara z Mahakamu, żeby się do ciebie dokopać.",
"Nigdy nie ma się drugiej okazji, żeby zrobić pierwsze wrażenie. Chodź, napijemy się lepiej piwa.",
"- Rzekł wtedy mężny Foltest: Cny Radowidzie... - Jaskier... co ty pieprzysz?",
"Nie cza s żałować kapusty, gdy płonie las.",
"Dziad zdjął z głowy wielką futrzaną czapę i dostojnie roztoczył wokół siebie smród.",
"Gdzie ogiery kastrują tam nie zaszkodzi uważać i na własne jajca.",
"Zapachniało powiewem jesieni, Z wiatrem zimnym uleciał słów sens. Tak być musi, niczego nie mogą już zmienić Brylanty na końcach Twych rzęs.",
"Rybka albo pipka, jak to mawiają miejscowi.",
"Va'esse deireádh aep eigean. Coś się kończy.",
"Lepiej zaliczać się do niektórych, niż do wszystkich.",
"Masz lat blisko 40, wyglądasz na blisko 30, wyobrażasz sobie, że masz nieco ponad 20, a postępujesz, jakbyś miał niecałe 10.",
"Lambert cáen me a’báeth aep arse. Lambert może mnie pocałować w dupę.",
"Popularne na dworze króla Vizimira powiedzonko głosiło, że jeśli Dijkstra twierdzi, że jest południe, a dookoła panują nieprzebite ciemności, należy zacząć niepokoić się o losy słońca.",
"Nie gardzę szpiegami. Gardzę szpiegowaniem. I gardzę pogardą.",
"Widzieliście go? Rycerz chędożony! Herbowy! Trzy lwy w tarczy! Dwa srają, a trzeci warczy!",
"Nie ma już na świecie wiary ani prawdy, ale chyba istnieje na świecie rozsądek? Co, Jaskier? Jest jeszcze na świecie rozsądek? Czy już zostały na nim tylko skurwysyństwo i pogarda?",
"Ot, babska dola. Wielkie ambicje przekreśla zrujnowana macica.",
"Pomyliłeś niebo z gwiazdami odbitymi nocą na powierzchni stawu.",
"Czarodziejki, moi panowie, na nic tak nie lecą, jak na wyszukany bajer.",
"Gadacie tak mądrze, że aż łeb kręgiem wiruje. A przecie i tak wszystkie te mądrości koło tego się kręcą, co u baby pod kiecką. Filozofy zasrane.",
"Starzeję się. Zaczynam miewać skrupuły.",
"Daj, ać ja pobruszę, a ty skocz do piwnicy po (KURWIEGO SYNA VERNONA ROCHE'A).",
"To nie może być mowa wiązana, bo on nie bluźni, nie mamrocze i nie liczy sylab na palcach. Pisze w cichości, a zatem to proza.",
"Mieć pół miliona i nie mieć pół miliona, to jest w sumie cały milion.",
"Przyjdzie gości w gaciach powitać. Ale po prawdzie, jacy goście, takie i powitanie.",
"Ty, Bonhart, mylisz złodziejstwo z indywidualną przedsiębiorczością.",
"Zaiste, wielkiego trzeba zadufania i wielkiego zaślepienia, by posokę lejącą się z szafotu nazywać sprawiedliwością.",
"Czerwone z czerwonym, żółte z żółtym, białe z białym. Tak zszyj, a na pewno będzie dobrze. - chirurg Rusty o tym, jak należy zszyć człowieka po operacji.",
"Drugi przykład babskiej wszechmocy – kontynuował Yarpen Zigrin – to Geralt z Rivii, wiedźmin.",
"Gdzie głowy rąbią, tam uszy lecą.",
"Jak rzekła młodziutka Cerro do króla Vridanka na ich pierwszej schadzce: „Niebrzydka rzecz, ale czy ma jakieś zastosowanie praktyczne?”",
"Wiedz, że dziś, tu, na zamku Stygga, wysikałeś się pod huragan.",
"Zaiste, jak mawiał król Dezmod, zaglądnąłwszy po skończonej potrzebie do nocnika: „Rozum nie jest w stanie tego ogarnąć.”",
"Sam nie wiem, co o tym myśleć, jak powiedział król Dezmod, gdy przyłapano go na oszukiwaniu w karty.",
"Żarty na bok, jak powiedział król Dezmod, gdy wśród uczty goście nagle zaczęli sinieć i umierać.",
"Nie gustujące w mężczyznach nimfomanki poddawały w wątpliwość moją męskość, groziły gwałtem na jeżu, straszyły ciążą, ba, nawet orgazmem, i to takim, któremu nie towarzyszą rytualne ruchy."];l=a.length;r=Math.floor(Math.random()*l);r=r+": "+a[r];
